/api/getExercise/ API method implementation
ttiagojm/DailyMath pull request #14
Opened 2023-11-28 03:49 UTC by Finalshare90

2023-11-28 17:45 UTC, ttiagojm commented on back-end/src/controllers/Connection.py
Are you creating this class to decouple future code? 

Another thing, when instanciated an object of this class, the __init__ will only receive data in the future? If yes, then this class will be a dataclass and you should use [this](https://docs.python.org/3/library/dataclasses.html) instead.

2023-11-28 17:51 UTC, ttiagojm requested changes
Check my comments

2023-11-28 22:15 UTC, Finalshare90 commented on back-end/src/controllers/Connection.py
Are you creating this class to keep future code decoupled?
Yes, in future updates, i pretend to make a `sessionController` class to manage user cookies and "exercise sessions", and that requires a separated `dataclass` for each connection.

Another thing, when instanciated an object of this class, the init will only receive data in the future? If yes, then [this](https://docs.python.org/3/library/dataclasses.html) class will be a dataclass and you should use this instead.
_Done_: [https://github.com/ttiagojm/DailyMath/commit/ff5dfd93827c2f8d5a7b9c617cd84f6ca8bbdf5f](ff5dfd93)

2023-11-28 22:25 UTC, ttiagojm commented on back-end/src/controllers/Connection.py
Ok, why you removed `isMultiple?` And why `id` is annotaded with `int` but you passed a default value "0" (a string)?

About the idea of sessionController for multiple exercises, I don't if makes sense because will be a new exercise everyday ... but we discuss that later and decouple code is always good.

2023-11-28 23:11 UTC, Finalshare90 commented on back-end/src/controllers/Connection.py
> Ok, why you removed isMultiple? 

I noticed that the `isMultiple` attribute would be irrelevant to the get request, considering that the exercise table already includes a `is_multiple_choice` row, `isMultiple` would only be useful in a INSERT context.

 >And why id is annotaded with int but you passed a default value "0" (a string)?
 
 Error of mine, fixed in [3c6d3e4](https://github.com/ttiagojm/DailyMath/commit/3c6d3e4b05a0fc7c9fe485f677c28f381108b6f2). 
 
> About the idea of sessionController for multiple exercises, I don't if makes sense because will be a new exercise everyday ... but we discuss that later and decouple code is always good.

I'm going to open an issue ASAP explain in a better manner my idea.

2023-11-28 23:19 UTC, ttiagojm commented on back-end/src/controllers/Connection.py
Actually we will need a options attribute that should be sent empty if it is not multiple choice or fullfilled, otherwise.
I guess, a string attribute is enough.

2023-11-28 23:34 UTC, Finalshare90 commented on back-end/src/controllers/Connection.py
I guess i don't get it. 
In `__exercise:dict` we're already sending the options to the client, and abstain from sending any more extra load to the client, but i can add a empty options header, if you think it is really necessary.

2023-11-28 23:41 UTC, ttiagojm commented on back-end/src/controllers/Connection.py
Yeah, forget about it... i confused `RequestExercise` with `Connection`

2023-11-28 23:42 UTC, ttiagojm approved these changes

2023-11-29 17:49 UTC, ttiagojm commented on back-end/src/controllers/RequestExercise.py
For this to be a singleton you need to verifiy if __exercise is empty and only run the setter if it is empty, if not just ignore all the setter code.

2023-11-29 17:51 UTC, ttiagojm commented on back-end/src/main.py
`isAnotherDay()` will need to set __exercise from RequestExercise to an empty dict again.

2023-11-30 12:38 UTC, bugelseif approved these changes

2023-11-30 13:32 UTC, ProgramingIsTheFuture approved these changes

2023-11-30 14:02 UTC, merged